# Container for Omeka-S development intended to run on docker desktop.
# Paul Cote for Cambridge Historical Commission
version: "4.0.4"

services:

  db:
    image: mysql
    restart: always
    networks:
      - network1
    volumes:
      - mysql-data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: blabla 
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
      explicit_defaults_for_timestamp: 1

  adminer:        # Database management tool for MariaDB
    image: adminer
    restart: always
    networks:
      - network1 
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db

  omeka:          # This is the main web server for Omeka.  
    depends_on:
      - db
    image: cdash-omeka-dev-4.0.4
    restart: always
    networks:
      - network1 
    ports:
      - "80:80"
    links:
      - db:db
    volumes:

    ## Bind Mounts are defined  in docker desktop and may 
    ## subsequntly be managed through the ordinary windows filesystem 
    ## through \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes

      - cdash-persist:/var/www/html/persist
      - cdash-scans:/var/www/html/scans

volumes:
  mysql-data:
  cdash-persist:
     external: true
  cdash-scans:
     external: true
networks:
  network1:  
